BASE_PATH: http://leydelobby.cl
markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
profile_detail: true

name: Ley de Lobby
author: Fundación Ciudadano Inteligente
featured-image: //images/post/
url: http://leydelobby.cl
description: 
etiquetas: ''
twitter: ciudadanoi
twitter_slogan: ""
github: ciudadanointeligente
gravatar_url: http://gravatar.com/avatar/15c938035f91373cb36062d6ad4ef2e5
hashtag: '#LeydeLobby'

analytics :
  provider : google
  google :
      tracking_id : 'UA-12345678-9'
