BASE_PATH: http://ciudadanointeligente.github.io/lobby
markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
profile_detail: true

name: Ley de Lobby
author: Fundaci칩n Ciudadano Inteligente
featured-image: //images/post/
url: http://www.leydelobby.cl
description: Sitio de campa침a a favor de la aprobaci칩n de la ley del lobby.
etiquetas: lobby, ley de lobby, ley del lobby, Senador Hosain Sabag, Diputado Jorge Burgos, Diputado Alberto Cardemil, Diputado Guillermo Ceroni, Diputado Ernesto Silva, Diputado Arturo Squella, Senador Carlos Bianchi, Senador Eduardo Frei, Senador Jaime Orpis, Senador Fulvio Rossi
twitter: ciudadanoi
twitter_slogan: "Ya se acordaron las reglas del juego! En 3 meses entrar치 en vigencia la ley de #Lobby"
github: ciudadanointeligente
gravatar_url: http://gravatar.com/avatar/15c938035f91373cb36062d6ad4ef2e5
hashtag: '#LeydeLobby'

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-46734534-1'
